document.getElementById("player").addEventListener("init",PlayerInit);
var player = new Playerjs({id:"player", "file":
[
{"title":"Indian Languages","folder":
[
{"title":"<img src='https://i.imgur.com/zWxcgrR.png' width='64px'height='36px'> Faith TV","file":"https://faithtvlive.livebox.co.in/faithtvhls/live.m3u8"},
{"title":"<img src='https://i.imgur.com/3RTWfwf.jpg' width='64px'height='36px'> Alpha TV","file":"https://account11.livebox.co.in/thealphatvhls/live.m3u8"},
{"title":"<img src='https://i.imgur.com/lyA55jh.jpg' width='64px'height='36px'> TamilChristian TV","file":"https://server2.thewebworld.in:3909/stream/play.m3u8"},
{"title":"<img src='https://i.imgur.com/UnuDHW9.jpg' width='64px'height='36px'> Family Channel","file":"https://2-fss-2.streamhoster.com/pl_118/amlst:203324-1410936/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/6b3nJcD.png' width='64px'height='36px'> Adhisayam TV","file":"https://livetv.adhisayamtv.org/adhisayamtv/83a062a18a761b948a73ad2ba7747a8f.sdp/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/CjhHzhz.png' width='64px'height='36px'> Angel TV","file":"https://wowzaprod270-i.akamaihd.net/hls/live/1007388/e7a2aac8/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/z8azsGr.png' width='64px'height='36px'> Channel 316","file":"https://channel316.livebox.co.in/c316hls/live.m3u8"},
{"title":"<img src='https://i.imgur.com/HVjc795.png' width='64px'height='36px'> Nambikkai TV","file":"https://live.wmncdn.net/nambikkaitv/live.stream/index.m3u8"},
{"title":"<img src='https://i.imgur.com/xLEGA5C.png' width='64px'height='36px'> Bible TV","file":"https://account33.livebox.co.in/bibletvhls/live.m3u8"},
{"title":"<img src='https://i.imgur.com/h9hsOt0.jpg' width='64px'height='36px'> GoRevival TV","file":"https://ktismaservers.in:3870/live/gorevivaltvlive.m3u8"},
{"title":"<img src='https://i.imgur.com/5EPBBIp.jpg' width='64px'height='36px'> Jebam TV","file":"https://server.iptelevision.in/hls/jebamtv.m3u8"},
{"title":"<img src='https://i.imgur.com/cPUOSyD.jpg' width='64px'height='36px'> Jesus TV Canada","file":"https://server1.thewebworld.in:3996/stream/play.m3u8"},
{"title":"<img src='https://i.imgur.com/Z1PvVYR.jpg' width='64px'height='36px'> Nithyam TV","file":"https://account34.livebox.co.in/nithiyamtvhls/live.m3u8"},
{"title":"<img src='https://i.imgur.com/Csfg9QY.png' width='64px'height='36px'> HolyGod TV","file":"https://cdn3.wowza.com/1/UjJzUlNOUTkvNWRG/M21RYWpy/hls/live/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/k9PEoM2.png' width='64px'height='36px'> LifeTV","file":"https://lifetv.livebox.co.in/lifetvtamilhls/live.m3u8"},
{"title":"<img src='https://i.imgur.com/5yi1uuA.png' width='64px'height='36px'> Jeyam TV","file":"https://jeyamtv.livebox.co.in/JeyamTelevisionhls/JeyamTelevision.m3u8"},
{"title":"<img src='https://i.imgur.com/CX4QpDl.png' width='64px'height='36px'> Joy TV","file":"https://joytv.livebox.co.in/joytvhls/live.m3u8"},
{"title":"<img src='https://i.imgur.com/ZHRqVc3.png' width='64px'height='36px'> Grace TV","file":"http://209.58.177.175/gracehls/live.m3u8"},
{"title":"<img src='https://i.imgur.com/ozvCUrc.png' width='64px'height='36px'> Heaven TV","file":"http://209.58.160.179/heaventvhls/live.m3u8"},
{"title":"<img src='https://i.imgur.com/h8gsBkL.png' width='64px'height='36px'> Grace TV","file":"https://gracetvcgl.livebox.co.in/Gracetvhls/Gracetv.m3u8"},
{"title":"<img src='https://i.imgur.com/sezFpQG.jpg' width='64px'height='36px'> Meetpar TV","file":"https://server2.thewebworld.in:3221/stream/play.m3u8"},
{"title":"<img src='https://i.imgur.com/zzKu53u.png' width='64px'height='36px'> Madha TV","file":"http://103.109.45.5:1935/madhatv/madhatv.stream_HDp/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/pyJTw5G.png' width='64px'height='36px'> Ruah TV","file":"https://iptelevision.in/hls/ruahtv.m3u8"},
{"title":"<img src='https://i.imgur.com/3UDjX1H.png' width='64px'height='36px'> Lord TV","file":"https://f-tx-edge-86.christianworldmedia.com/lordtvministries/mp4:lordtvministries/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/8MqbxPt.png' width='64px'height='36px'> FCM TV","file":"https://f-tx-edge-87.christianworldmedia.com/FCMTV01/mp4:FCMTV01/chunklist.m3u8"},
{"title":"<img src='https://i.imgur.com/7ziVIiG.png' width='64px'height='36px'> Aseervatham TV","file":"https://stream.blessingtv.tv:1443/blessingtv-tamillive/mystream_480p/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/sjZO7Iv.png' width='64px'height='36px'> IBC Siluvai","file":"https://tx1.ibctamil.tv/CDN_IBC_Siluvai/tracks-v1a1/mono.m3u8"},
{"title":"<img src='https://i.imgur.com/ExImjuu.png' width='64px'height='36px'> Shubhavartha TV","file":"https://live.wmncdn.net/shubhavartha/live.stream/index.m3u8"},
{"title":"<img src='https://i.imgur.com/pXRZxDx.png' width='64px'height='36px'> NireekshanaTV","file":"https://calvary.livebox.co.in/NireekshanaTVhls/live.m3u8"},
{"title":"<img src='https://i.imgur.com/7qqeIHE.jpg' width='64px'height='36px'> RakshanaTV","file":"https://6n3yopznd9ok-hls-live.5centscdn.com/RAKSHANA/271ddf829afeece44d8732757fba1a66.sdp/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/6ndMpqN.png' width='64px'height='36px'> HopeTV India","file":"https://hcintlinc.mmdlive.lldns.net/hcintlinc/d6f52a14a11d490191712e4e2b91ba21/manifest.m3u8"},
{"title":"<img src='https://i.imgur.com/cPLmhB4.png' width='64px'height='36px'> New Hope TV","file":"https://shashwatha.com/hls/show/newhopetv.m3u8"},
{"title":"<img src='https://i.imgur.com/k9PEoM2.png' width='64px'height='36px'> Life TV","file":"https://lifetv.livebox.co.in/lifetvhls/lifetv.m3u8"},
{"title":"<img src='https://i.imgur.com/lv3j3jf.jpg' width='64px'height='36px'> Hallelujah TV","file":"https://jctechworld.live/Hallelujahhls/Hallelujah.m3u8"},
{"title":"<img src='https://i.imgur.com/HFPyZvt.jpg' width='64px'height='36px'> Gospel TV India","file":"http://live.adostream.com:1935/gospeltv/gospeltv/chunklist.m3u8"},
{"title":"<img src='https://i.imgur.com/Vo9IHTd.png' width='64px'height='36px'> BigJ TV","file":"https://bigjtv.livebox.co.in/bigjtvhls/live.m3u8"},
{"title":"<img src='https://i.imgur.com/D2Ool43.jpg' width='64px'height='36px'> Divine Vision","file":"https://divineplayout-us2.tulix.tv/live/Stream1/.m3u8"},
{"title":"<img src='https://i.imgur.com/rry062n.png' width='64px'height='36px'> Shekainah TV","file":"https://121tv.livebox.co.in/ShekainahTvhls/shekainahtvlive.m3u8"},
{"title":"<img src='https://i.imgur.com/yIfCWtL.png' width='64px'height='36px'> Marian World","file":"https://ewmoy8w4y2a7-hls-live.5centscdn.com/mariantv/d0dbe915091d400bd8ee7f27f0791303.sdp/mono.m3u8"},
{"title":"<img src='https://i.imgur.com/9650p8L.png' width='64px'height='36px'> JN Vision","file":"https://live.wmncdn.net/jnvisiontv/0e1fd802947a734b3af7787436f11588.sdp/index.m3u8"},
{"title":"<img src='https://i.imgur.com/foCMe0h.jpg' width='64px'height='36px'> Gospel TV","file":"https://stream.e2is.in/hls/gospeltv.m3u8"},
{"title":"<img src='https://i.imgur.com/UAwPvla.png' width='64px'height='36px'> Harvest TV","file":"https://live.wmncdn.net/harvesttvlive1/bbb19eae240ec100af921d511efc86a0.sdp/index.m3u8"},
{"title":"<img src='https://i.imgur.com/1Ps7ZXY.png' width='64px'height='36px'> Harvest TV Malayalam","file":"https://live.wmncdn.net/harvestenglish/d1796a22d24e8696c7d5d0b5c349fdd2.sdp/index.m3u8"},
{"title":"<img src='https://i.imgur.com/sRoDa2k.png' width='64px'height='36px'> HarvestTV USA","file":"https://live.wmncdn.net/harvestusa/d57ffba6564caea2fee3f4085f19a098.sdp/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/d3lkqa6.png' width='64px'height='36px'> HarvestTV Arabia","file":"https://live.wmncdn.net/harvesttvkuwait/bbb19eae240ec100af921d511efc86a0.sdp/index.m3u8"},
{"title":"<img src='https://i.imgur.com/LtEqF8X.png' width='64px'height='36px'> ACB Channel","file":"http://209.58.177.213/maranathahls/maranatha.m3u8"},
{"title":"<img src='https://i.imgur.com/880Rt52.png' width='64px'height='36px'> Shubsandesh TV","file":"https://live.wmncdn.net/shubhsandeshtv1/live123.stream/index.m3u8"},
{"title":"<img src='https://i.imgur.com/zcx840Q.jpg' width='64px'height='36px'> Revive India","file":"https://yzmq2nyyqvax-hls-live.wmncdn.net/1477_push_382/0306342d232c506956d1953de849256a.sdp/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/midCLSB.png' width='64px'height='36px'> YeshuaaTV","file":"http://cdn15.live247stream.com/yeshuaa/tv/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/kEjfWdN.png' width='64px'height='36px'> PrarthanaTV","file":"http://nettv4k.com:8000/live/pbtv/pbtv/576.m3u8"},
{"title":"<img src='https://i.imgur.com/3bZO7LX.png' width='64px'height='36px'> Zindagi TV","file":"http://live.urdustreamz.net:1935/live_transcoder/ngrp:zindagitv.stream_all/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/EtXGDEB.png' width='64px'height='36px'> Kanal 10 Asia","file":"http://cdn-kanal10.crossnet.net:1935/kanal10/kanal10asia/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/IgW4ruC.png' width='64px'height='36px'> KING TV","file":"https://streamer12.vdn.dstreamone.net/kingtv/kingtv/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/QT9gUEC.png' width='64px'height='36px'> ISAAC TV","file":"https://livecdn.live247stream.com/isaac/tv/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/OIIijRh.png' width='64px'height='36px'> FAZAL TV","file":"https://livecdn.live247stream.com/fazal/tv/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/IZNV064.png' width='64px'height='36px'> BARKAT TV","file":"https://streamer12.vdn.dstreamone.net/barkattv/dexpo/playlist.m3u8?720p"},
{"title":"<img src='https://i.imgur.com/j7Ox5CF.png' width='64px'height='36px'> StarShine TV","file":"https://f-tx-edge-86.christianworldmedia.com/ShineStarTV/mp4:ShineStarTV/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/8ARp8lI.png' width='64px'height='36px'> BTL TV","file":"https://livecdn.live247stream.com/btl/tv/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/rsScDYr.png' width='64px'height='36px'> JAIRUS TV","file":"https://livecdn.live247stream.com/jairus/tv/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/8nrJVrb.png' width='64px'height='36px'> GAWAHI TV","file":"https://livecdn.live247stream.com/gawahi/tv/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/2YgEHeS.png' width='64px'height='36px'> Mission Asia","file":"https://livecdn.live247stream.com/missionasia/tv/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/y71XPfB.png' width='64px'height='36px'> Joystar TV","file":"https://cdn.live247stream.com/joystar/tv/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/NI5imBM.png' width='64px'height='36px'> EternalLife TV","file":"https://livecdn.live247stream.com/eternallife/tv/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/wBLQc2G.png' width='64px'height='36px'> Praise TV","file":"https://livecdn.live247stream.com/praise/tv/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/faI75U7.png' width='64px'height='36px'> Bible TV Global","file":"https://livecdn.live247stream.com/thebible/tv/playlist.m3u8"}
]},
{"title":"English","folder":
[
{"title":"<img src='https://i.imgur.com/BKz6lH6.png' width='64px'height='36px'> Bible Screen","file":"https://biblescreen.faithlifecdn.com/biblescreen/bibleScreen/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/MoPJ108.jpg' width='64px'height='36px'> The Word Network","file":"https://clouditize-lh.akamaihd.net/i/clouditize_live@16871/master.m3u8"},
{"title":"<img src='https://i.imgur.com/XH14Uc6.png' width='64px'height='36px'> It is Written","file":"https://itiswrittentv.akamaized.net/xR8gyATuHMVx69u9G79DXnpNRL/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/AYukXKp.jpg' width='64px'height='36px'> Bible Discovery","file":"https://2-fss-2.streamhoster.com/pl_138/amlst:200226-1452410/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/15u7nbG.png' width='64px'height='36px'> GodTV UK","file":"https://zypelive-lh.akamaihd.net/i/default_1@745545/master.m3u8?"},
{"title":"<img src='https://i.imgur.com/McuYlYv.png' width='64px'height='36px'> GODTV US","file":"https://zypelive-lh.akamaihd.net/i/default_1@710958/master.m3u8?"},
{"title":"<img src='https://i.imgur.com/vEEoWh8.png' width='64px'height='36px'> Prayer Room","file":"https://zypelive-lh.akamaihd.net/i/default_1@745546/master.m3u8?"},
{"title":"<img src='https://i.imgur.com/LlWQVWD.png' width='64px'height='36px'> GODTV Asia","file":"https://zypelive-lh.akamaihd.net/i/default_1@745543/master.m3u8?"},
{"title":"<img src='https://i.imgur.com/B6Vj0DN.png' width='64px'height='36px'> GODTV Africa","file":"https://zypelive-lh.akamaihd.net/i/default_1@745544/master.m3u8?"},
{"title":"<img src='https://i.imgur.com/h8BCajX.png' width='64px'height='36px'> GODTV Australia","file":"https://zypelive-lh.akamaihd.net/i/default_1@745528/master.m3u8?"},
{"title":"<img src='https://i.imgur.com/fqk3lky.png' width='64px'height='36px'> GODTV Live","file":"https://zypelive-lh.akamaihd.net/i/default_1@745547/master.m3u8?"},
{"title":"<img src='https://i.imgur.com/UjYcj3T.png' width='64px'height='36px'> FaithWorld TV","file":"https://faithtv.sechls01.visionip.tv/live/faithtv-faithtvweb-faithtv-SDq/chunklist.m3u8"},
{"title":"<img src='https://i.imgur.com/FoHnXhK.png' width='64px'height='36px'> TV MANA ","file":"http://c2.manasat.com:1935/church-online/ingles2/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/GJrxreM.png' width='64px'height='36px'> Genesis Science Network","file":"https://katapy.hs.llnwd.net/gsntv/genesissciencenetworktv/ngrp:genesissciencenetworktv_all/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/TbyIpie.png' width='64px'height='36px'> HopeTV International","file":"https://hcintlinc.mmdlive.lldns.net/hcintlinc/60f14a7fec64454e90712421a46ac6f1/manifest.m3u8"},
{"title":"<img src='https://i.imgur.com/WNGS4U5.png' width='64px'height='36px'> GoodNews TV","file":"https://live.wmncdn.net/goodnews/live.stream/index.m3u8"},
{"title":"<img src='https://i.imgur.com/pKC8bgd.png' width='64px'height='36px'> GospelTruth TV","file":"https://playout.zype.com/channel_manifest/6113f4ec7293b800015f808e/live.m3u8?ad_enabled=false&amp;api_key=lme28nzzmpUhyudZK-aAtYVcZ5zUFWl9OpJ77GwDrPcGi6cExyVuoKU6YwR-n_Mw&amp;app_key=v8GR3uygk0s9NdbJ6wyJFp3Z3dZpTU9Zdb75ljtk4-SMekzDZLcsbKvwykGnBQq-&amp;player_request_id=611cf3b72150150001fb3e01"},
{"title":"<img src='https://i.imgur.com/bICAtXN.png' width='64px'height='36px'> Victory Channel","file":"https://content-z.uplynk.com/channel/ea37a0934a0749fe80f493b402ce5908.m3u8"},
{"title":"<img src='https://i.imgur.com/oaQTqy7.jpg' width='64px'height='36px'> Super Channel","file":"https://uaez75u-lh.akamaihd.net/i/test_1@49298/master.m3u8"},
{"title":"<img src='https://i.imgur.com/vwRE432.png' width='64px'height='36px'> Firstlight TV","file":"https://uni01rtmp.tulix.tv/firstlight/firstlight.smil/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/LfoQjmw.png' width='64px'height='36px'> 3ABN","file":"https://moiptvhls-i.akamaihd.net/hls/live/652042/secure/index.m3u8"},
{"title":"<img src='https://i.imgur.com/V9qOKM0.png' width='64px'height='36px'> 3ABN International","file":"https://moiptvhls-i.akamaihd.net/hls/live/652312/secure/master.m3u8"},
{"title":"<img src='https://i.imgur.com/83o1ACs.png' width='64px'height='36px'> 3ABN Praise","file":"https://moiptvhls-i.akamaihd.net/hls/live/554145/secure/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/ywkvfX7.png' width='64px'height='36px'> 3ABN Proclaim","file":"https://moiptvhls-i.akamaihd.net/hls/live/652317/secure/master.m3u8"},
{"title":"<img src='https://i.imgur.com/HagrTlb.png' width='64px'height='36px'> 3ABN Dare To Dream","file":"https://moiptvhls-i.akamaihd.net/hls/live/652313/secure/master.m3u8"},
{"title":"<img src='https://i.imgur.com/A5pFdfC.png' width='64px'height='36px'> EWTN Asia Pacific","file":"https://cdn3.wowza.com/1/QmVNUVhTNTZSS3Uz/YWQ0aHpi/hls/live/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/2DYuLaS.png' width='64px'height='36px'> EWTN Africa/Asia","file":"https://cdn3.wowza.com/1/ZVBYYXFLLzE0c3NC/Qk1FMURC/hls/live/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/fYJ2xVZ.png' width='64px'height='36px'> EWTN Canada","file":"https://cdn3.wowza.com/1/YW5wSWZiRGd2eFlU/bGV0aVBq/hls/live/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/tDuILZF.png' width='64px'height='36px'> EWTN Europe","file":"https://cdn3.wowza.com/1/T2NXeHF6UGlGbHY3/WFluRldQ/hls/live/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/wMATF6i.png' width='64px'height='36px'> SALT and LIGHT","file":"https://zm6gdaxeyn93-hls-live.5centscdn.com/slworld/d65ce2bdd03471fde0a1dc5e01d793bb.sdp/index.m3u8"},
{"title":"<img src='https://i.imgur.com/PLi7JiE.png' width='64px'height='36px'> Catholic Life","file":"https://2-fss-2.streamhoster.com/pl_120/amlst:205324-2014804/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/CvWoXNu.png' width='64px'height='36px'> New Evangelization TV","file":"https://desales.pc.cdn.bitgravity.com/cdn-live/_definst_/desales/live/feed02/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/wtQDMpD.png' width='64px'height='36px'> Catholic Faith Network","file":"https://uni8rtmp.tulix.tv/cfntv/cfntv/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/qisLfuc.png' width='64px'height='36px'> Catholic TV","file":"https://catholictvhd-lh.akamaihd.net/i/ctvhd_1@88148/master.m3u8"},
{"title":"<img src='https://i.imgur.com/DiVdljY.png' width='64px'height='36px'> FaithLife TV","file":"https://biblescreen.faithlifecdn.com/biblescreen/faithlifetv/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/KrDYGRM.png' width='64px'height='36px'> BetterLife TV","file":"https://uni10rtmp.tulix.tv/betterlife/betterlife.stream/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/jQFGkLP.png' width='64px'height='36px'> BetterHealth TV","file":"https://uni10rtmp.tulix.tv/betterhealth/betterhealth.stream/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/WoVfugd.png' width='64px'height='36px'> BetterNature TV","file":"https://uni10rtmp.tulix.tv/betternature/betternature.stream/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/4NfQ2bq.png' width='64px'height='36px'> CYC","file":"https://5a8308add0b31.streamlock.net/cycnow.com/cyc.smil/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/QNIUqlw.png' width='64px'height='36px'> ISN TV","file":"https://cpdc101-lh.akamaihd.net/i/ISNCPDCMB1_1@314337/master.m3u8"},
{"title":"<img src='https://i.imgur.com/koYnH8A.jpg' width='64px'height='36px'> GBN Network","file":"https://wowzaprod198-i.akamaihd.net/hls/live/787209/0d8d1ac2/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/IK73tkJ.png' width='64px'height='36px'> GoodLife 45","file":"https://1-fss29-s0.streamhoster.com/lv_goodlife45f1/_definst_/broadcast1/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/5jz0f93.png' width='64px'height='36px'> Cornerstone Network","file":"https://cdn-media9-truegod.r.worldssl.net/ctvnlive/smil:ctvn.smil/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/eTeRBNy.png' width='64px'height='36px'> Gospel Channel","file":"https://169lawskfzaua3opl.hlscdn.obs-server.com/hls/puc9djrh2cg7wjqw8v9was5fu5kh4a.m3u8"},
{"title":"<img src='https://i.imgur.com/jSJuG1L.png' width='64px'height='36px'> CTN","file":"https://rrsatrtmp.tulix.tv/ctntv/ctntvmulti.smil/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/6eDlamn.png' width='64px'height='36px'> Amazing Discoveries","file":"https://uni01rtmp.tulix.tv/amazingdtv/amazingdtv/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/jl3Br7G.png' width='64px'height='36px'> BETV","file":"http://stream.iphonewebtown.com:1935/bibleexplorations/bexplorations.stream/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/BzrvLMj.jpg' width='64px'height='36px'> His Channel","file":"https://www3.hischannel.com/liveedge/smil:hls.smil/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/xdgZkvh.jpg' width='64px'height='36px'> SBN","file":"https://sonlife7-i.akamaihd.net/hls/live/585011/ch7/master.m3u8"},
{"title":"<img src='https://i.imgur.com/iTWnDOw.png' width='64px'height='36px'> Gods Learning Channel","file":"https://2-fss-1.streamhoster.com/pl_122/200562-1176456-1/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/vqg3iYj.png' width='64px'height='36px'> Spirit Television","file":"https://cdnlive.myspirit.tv/LS-ATL-43240-2/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/hDNpvfR.png' width='64px'height='36px'> Mission TV ","file":"http://192.111.77.87:1935/live/missiontv_720p/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/cYbSVgS.jpg' width='64px'height='36px'> Life End Times TV","file":"https://2-fss-2.streamhoster.com/pl_138/200226-1359204-1/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/Q6QD58E.png' width='64px'height='36px'> LoveWorld TV","file":"https://c6v6m6p7.stackpathcdn.com/lwsat/lwsatmobile/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/Sizq2D0.png' width='64px'height='36px'> JewishLife TV","file":"https://streaming-a-1055.cdn.nextologies.com/ab6b5c32d6ba17d9/47d118670709893b/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/QqFjpEl.png' width='64px'height='36px'> NRB","file":"https://uni6rtmp.tulix.tv/nrbnetwork/myStream.sdp/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/evigh7j.png' width='64px'height='36px'> CBN","file":"https://bcliveuniv-lh.akamaihd.net/i/iptv1_1@194050/master.m3u8"},
{"title":"<img src='https://i.imgur.com/ILLHFTi.png' width='64px'height='36px'> World Harvest TV","file":"https://597865f6e4114.streamlock.net/live/leseaorigin.stream/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/Mn1vZzs.png' width='64px'height='36px'> Inspiration TV","file":"https://inspnetworks-lh.akamaihd.net/i/insp_2@393793/master.m3u8"},
{"title":"<img src='https://i.imgur.com/2pklRoS.png' width='64px'height='36px'> Revelation TV","file":"https://rtv.cdn.mangomolo.com/rtv/smil:rtv.stream.smil/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/dWuBLgJ.png' width='64px'height='36px'> Lifevision TV","file":"https://uni5rtmp.tulix.tv/lifevision/lifevision.stream/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/I8CXnfR.jpg' width='64px'height='36px'> FFE TV","file":"https://uni8rtmp.tulix.tv/ffetv/myStream.sdp/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/0XkpgXH.jpg' width='64px'height='36px'> CTN Lifestyle","file":"https://ctntv.getstreamhosting.com:1936/Lifestyle/Lifestyle/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/FA0Pqkn.jpg' width='64px'height='36px'> HBN TV","file":"https://cdnvideo.webvideocore.net/enc4_rq3ifrpkhtbr8k1n45ftha42nb2msj8mrb4fsal5frgsqnai0nbt354pi5cdd6154l35o8ij909d45ueipsosstqvgemc59vmidsfnq2ak7fqu6o1ifqt2vmpfanb3qb2/index.m3u8"},
{"title":"<img src='https://i.imgur.com/EewHwCY.jpg' width='64px'height='36px'> Blue Mountain TV","file":"https://vse2-as-all85.secdn.net/bmt-live/play/bmt_1.smil/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/LIckl8c.png' width='64px'height='36px'> Watchmen Broadcasting","file":"https://2-fss-2.streamhoster.com/pl_120/amlst:200226-1233458/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/4PhDIL7.jpg' width='64px'height='36px'> True Word Network","file":"https://glorystartv.live/TrueWordNetwork/index.m3u8"},
{"title":"<img src='https://i.imgur.com/bINE7HQ.jpg' width='64px'height='36px'> Life Destiny TV","file":"https://cdnvideo.webvideocore.net/enc4_l6lkamfi43fsatgtgufhr5dldv2baiuhlo6i6empdvrdufeg8iaprg63eaf48n1ro3ev4j1292qnkc5u38071vtelg11k0f8fefqc57vmt5fd5d531kf7290bca26ce6t/index.m3u8"},
{"title":"<img src='https://i.imgur.com/q3iiP7n.jpg' width='64px'height='36px'> GEB Network","file":"https://5abbf4687b6ea.streamlock.net/live/smil:geb/index.m3u8"},
{"title":"<img src='https://i.imgur.com/rUd6QOg.png' width='64px'height='36px'> HopeNow TV","file":"https://klive.kaltura.com/s/env/cluster-1-a.live.nvp1/live/hls/p/2531852/e/1_eo1tazij/tl/main/st/0/t/E--AWYz5R0U7gm2ua9VKlA/index-s32.m3u8?__hdnea__=st=1640941258~exp=1641027658~acl=/s/env/cluster-1-a.live.nvp1/live/hls/p/2531852/e/1_eo1tazij/tl/main/st/0/t/E--AWYz5R0U7gm2ua9VKlA/index-s*~hmac=ddcfae9be791e67ed1755e01710d6563ad396e51f242f99f8184a6242ff88f69"}
]},
{"title":"World Languages","folder":
[
{"title":"<img src='https://i.imgur.com/qzJnYQc.png' width='64px'height='36px'> 3ABN Latino","file":"https://moiptvhls-i.akamaihd.net/hls/live/652315/secure/master.m3u8"},
{"title":"<img src='https://i.imgur.com/uWENkUi.png' width='64px'height='36px'> Alfa Omega","file":"http://s5.alfaomega.tv:1935/alfaomega/alfaomega1.sdp/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/eyrzhxZ.png' width='64px'height='36px'> CTNi","file":"https://584097344c1f0.streamlock.net/48/_definst_/smil:48.smil/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/vFchxNo.png' width='64px'height='36px'> Nuevo Tiempo","file":"http://stream.novotempo.com:1935/tv/tvnuevotiempo.stream/live.m3u8"},
{"title":"<img src='https://i.imgur.com/Q4ANaMk.png' width='64px'height='36px'> KKR TV","file":"http://stream.kkr.dk/live/ngrp:kkr_adaptive/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/wMbmIuo.png' width='64px'height='36px'> Hope Channel Polska","file":"https://stream.hopechannel.pl/livetv/colombo/hope.m3u8"},
{"title":"<img src='https://i.imgur.com/OA0vcop.png' width='64px'height='36px'> CDM Internacional","file":"http://205.164.56.130:1935/marcos536/marcos536/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/cn8jcEd.png' width='64px'height='36px'> Red ADVenir","file":"http://streamer1.streamhost.org:1935/salive/GMIredadvenirh/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/TOlEzOC.png' width='64px'height='36px'> Santuario de Fatima","file":"http://213.13.26.11:1935/live/santuario.stream/livestream.m3u8"},
{"title":"<img src='https://i.imgur.com/U84VX3p.png' width='64px'height='36px'> Novo Tempo","file":"http://stream.novotempo.com:1935/tv/tvnovotempo.smil/live.m3u8"},
{"title":"<img src='https://i.imgur.com/UBPoKZG.png' width='64px'height='36px'> Igreja Online","file":"http://195.22.11.11:1935/igronline/igronline2/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/CxP9f1n.png' width='64px'height='36px'> TV Mana1 Portugal","file":"http://195.22.11.11:1935/tvmana/tvmana2/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/23f8KAF.png' width='64px'height='36px'> Igreja Universal","file":"https://644398c.ha.azioncdn.net/primary/tvuniversal_480p.sdp/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/DQQi5zf.png' width='64px'height='36px'> Rede Gospel","file":"https://cdn.jmvstream.com/w/LVW-8719/LVW8719_AcLVAxWy5J/chunklist.m3u8"},
{"title":"<img src='https://i.imgur.com/MDLN52K.png' width='64px'height='36px'> 3ABN Francais","file":"https://moiptvhls-i.akamaihd.net/hls/live/652314/secure/master.m3u8"},
{"title":"<img src='https://i.imgur.com/PvJSHJ9.png' width='64px'height='36px'> KTO","file":"https://livehdkto-lh.akamaihd.net/i/LiveStream_1@178944/index_1200_av-p.m3u8?sd=10&rebase=on"},
{"title":"<img src='https://i.imgur.com/PYmGW3h.png' width='64px'height='36px'> TV 2000 Italy","file":"http://mi1.wz.tv2000.it:80/tv2000_alfa.m3u8"},
{"title":"<img src='https://i.imgur.com/wTAnGrt.png' width='64px'height='36px'> 4E Greece","file":"http://eu2.tv4e.gr:1935/live/smil:myStream.sdp.smil/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/oC3A7xj.png' width='64px'height='36px'> Himlen TV 7","file":"http://vod.tv7.fi:1935/tv7-se/_definst_/smil:tv7-se.smil/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/ON73UGa.png' width='64px'height='36px'> Kanal 10 Norge","file":"http://cdn-kanal10.crossnet.net/kanal10no/live1/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/IjCbyzt.png' width='64px'height='36px'> Die Neue Zeit","file":"https://www.onairport.live/die-neue-zeit-tv-live/livestream_high/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/MnMnRf9.png' width='64px'height='36px'> Небеса TV7","file":"http://vod.tv7.fi:1935/tv7-ru/_definst_/smil:tv7-ru.smil/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/aqjY4pg.png' width='64px'height='36px'> Три Ангела","file":"https://hls.tv.3angels.ru/stream.m3u8"},
{"title":"<img src='https://i.imgur.com/TYTBhKK.png' width='64px'height='36px'> Taevas TV7","file":"https://vod.tv7.fi/tv7-ee/_definst_/smil:tv7-ee.smil/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/Jsml4lD.png' width='64px'height='36px'> Credo TV","file":"http://cdn.credonet.tv:1935/ctv/smil:livecredo.smil/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/qM7nvNZ.png' width='64px'height='36px'> TV7 Finland","file":"https://vod.tv7.fi/tv7-fi/_definst_/smil:tv7-fi.smil/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/CYsycLM.png' width='64px'height='36px'> Hossanna Vision (ES)","file":"https://1206618505.rsc.cdn77.org/LS-ATL-59020-1/index.m3u8"},
{"title":"<img src='https://i.imgur.com/V00tmp8.png' width='64px'height='36px'> EWTN Espana","file":"https://cdn3.wowza.com/1/SmVrQmZCUXZhVDgz/b3J3MFJv/hls/live/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/96tsgcC.png' width='64px'height='36px'> LVM (DO)","file":"https://uni01rtmp.tulix.tv/playout2multi9/lavozdemaria.stream/index.m3u8"},
{"title":"<img src='https://i.imgur.com/atqvDiw.png' width='64px'height='36px'> Mision El TV (DO)","file":"https://5790d294af2dc.streamlock.net/8286/8286/index.m3u8"},
{"title":"<img src='https://i.imgur.com/AO1m4da.png' width='64px'height='36px'> Telebendicion (DO)","file":"http://ss8.domint.net:2124/tbt_str/telebendicion/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/5tKFlZy.png' width='64px'height='36px'> Aghapy TV (EG)","file":"http://46.105.112.176:1935/aghapy.tv/aghapy.smil/index.m3u8"},
{"title":"<img src='https://i.imgur.com/mOFtX6A.png' width='64px'height='36px'> Light Channel (DE)","file":"http://streamer1.streamhost.org:1935/salive/lctvde/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/GP97d1c.png' width='64px'height='36px'> Sophia TV (DE)","file":"https://www.onairport.live/sophiatv-it-live/livestream_low/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/uklPhwn.png' width='64px'height='36px'> TV Mana (FR)","file":"http://c2.manasat.com:1935/eglise-online/frances3/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/Cvkr78V.png' width='64px'height='36px'> Dieu TV","file":"https://katapy.hs.llnwd.net/dieutvwza1/DIEUTVLIVE/smil:dieutv.smil/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/5VTqjMh.png' width='64px'height='36px'> KTV Austria","file":"http://d1pz8zear993v8.cloudfront.net/hlsme/kathtv.m3u8"},
{"title":"<img src='https://i.imgur.com/Yn2frtl.png' width='64px'height='36px'> Genesis TV","file":"http://201.144.184.98:1935/genesis/smil:television.smil/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/JcK7ypp.png' width='64px'height='36px'> Life TV","file":"https://lifetv.mpks.sk/s.m3u8"},
{"title":"<img src='https://i.imgur.com/PLsnrtjt.png' width='64px'height='36px'> Life TV","file":"http://lifetv.bitflip.ee/live/stream1.m3u8"},
{"title":"<img src='https://i.imgur.com/Q3U3Edb.jpg' width='64px'height='36px'> Alfa TV","file":"https://alfatv.digitacdn.net/live/_definst_/alfatv/amlst:alfatv.amlst/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/MV5vkxo.png' width='64px'height='36px'> Aliento Vision ","file":"https://livestreamcdn.net:444/Alientoenvivo/smil:Alientoenvivo.smil/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/2WFqobq.jpg' width='64px'height='36px'> C Sat TV","file":"https://5d658d7e9f562.streamlock.net/csat.tv/csat.smil/playlist.m3u8"}
]},
{"title":"Kids","folder":
[
{"title":"<img src='https://i.imgur.com/oVq4Jg6.png' width='64px'height='36px'> 3ABN Kids","file":"https://moiptvhls-i.akamaihd.net/hls/live/652318/secure/master.m3u8"},
{"title":"<img src='https://i.imgur.com/EvrI7lk.png' width='64px'height='36px'> PBS Kids","file":"https://2-fss-2.streamhoster.com/pl_140/amlst:200914-1298290/playlist.m3u8?DVR"},
{"title":"<img src='https://i.imgur.com/IkIj1zw.jpg' width='64px'height='36px'> Akaram Kidz","file":"http://akaram.zecast.net/akaram-live/akaramkidz/index.m3u8"},
{"title":"<img src='https://i.imgur.com/jQ6xvvA.png' width='64px'height='36px'> TVO Kids","file":"https://bcsecurelivehls-i.akamaihd.net/hls/live/623607/15364602001/tvokids/master.m3u8"},
{"title":"<img src='https://i.imgur.com/ohj9jiv.jpg' width='64px'height='36px'> Knowledge Kids","file":"https://d1wal6k3d7ssin.cloudfront.net/out/v1/ea91db0906c847a4931b46a9ec36e77b/index.m3u8"},
{"title":"<img src='https://i.imgur.com/RTjgDbY.jpg' width='64px'height='36px'> Kidz BOP","file":"https://kidzbop-rokuus.amagi.tv/kidzbop-roku/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/HlliW3r.png' width='64px'height='36px'> Duck TV","file":"https://mmm-ducktv-2-it.samsung.wurl.com/manifest/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/RC1ZjhP.png' width='64px'height='36px'> Lego TV","file":"https://legochannel-roku.amagi.tv/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/DWJNRiZ.png' width='64px'height='36px'> KetchupTV","file":"https://aa8019675b784a8f86008d57eaefb016.mediatailor.us-east-1.amazonaws.com/v1/master/04fd913bb278d8775298c26fdca9d9841f37601f/Samsung-gb_Ketchup/playlist.m3u8?ads.wurl_channel=950&ads.wurl_name=Ketchup&ads.coppa=1&ads.psid=%7BPSID%7D&ads.targetopt=%7BTARGETOPT%7D&ads.app_domain=%7BAPP_DOMAIN%7D&ads.app_name=%7BAPP_NAME%7D&ads.consent=%7BTC_STRING%7D"},
{"title":"<img src='https://i.imgur.com/eM5gxCa.jpg' width='64px'height='36px'> Happy Kids TV","file":"https://happykids-roku.amagi.tv/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/pO00moR.png' width='64px'height='36px'> KidoodleTV","file":"https://06fda8bb401f4c0abb854097c0a3b3d6.mediatailor.us-east-1.amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/Samsung_KidoodleTV/playlist.m3u8?ads.us_privacy=1YNY&ads.wurl_channel=414&ads.wurl_name=KidoodleTV&ads.psid=%7BPSID%7D&ads.targetopt=%7BTARGETOPT%7D&ads.app_domain=%7BAPP_DOMAIN%7D&ads.app_name=%7BAPP_NAME%7D&ads.coppa=1"},
{"title":"<img src='https://i.imgur.com/7Q0WCwZ.png' width='64px'height='36px'> Moonbug Kids","file":"https://moonbug-rokuus.amagi.tv/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/UYigLv2.png' width='64px'height='36px'> TG Junior","file":"https://tg-junior.samsung.wurl.com/manifest/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/XSgcQGy.png' width='64px'height='36px'> Toon Goggles","file":"https://toon-goggles.samsung.wurl.com/manifest/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/bKtAfQJ.png' width='64px'height='36px'> The Pet Collective","file":"https://07f754f8f3aa4f45a494a61ff985a418.mediatailor.us-east-1.amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/Samsung-gb_ThePetCollective/playlist.m3u8?ads.wurl_channel=152&ads.wurl_name=ThePetCollective&ads.psid=%7BPSID%7D&ads.targetopt=%7BTARGETOPT%7D&ads.app_domain=%7BAPP_DOMAIN%7D&ads.app_name=%7BAPP_NAME%7D&ads.coppa=0&ads.consent=%7BTC_STRING%7D"},
{"title":"<img src='https://i.imgur.com/SmVMeP7.jpg' width='64px'height='36px'> SuperToons","file":"https://ba60d73b54dd41b68ae2a0601454ed52.mediatailor.us-east-1.amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/Samsung-gb_SuperToonsTV/playlist.m3u8?ads.wurl_channel=606&ads.wurl_name=SuperToonsTV&ads.psid=%7BPSID%7D&ads.targetopt=%7BTARGETOPT%7D&ads.app_domain=%7BAPP_DOMAIN%7D&ads.app_name=%7BAPP_NAME%7D&ads.coppa=1&ads.consent=%7BTC_STRING%7D"},
{"title":"<img src='https://i.imgur.com/GAfgYJj.png' width='64px'height='36px'> Zoo Moo","file":"https://8e3b9b86a94645d8b36c7722967c0086.mediatailor.us-east-1.amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/Samsung_Zoomoo/playlist.m3u8?ads.wurl_channel=644&ads.wurl_name=Zoomoo&ads.us_privacy=1YNY&ads.psid=%7BPSID%7D&ads.targetopt=%7BTARGETOPT%7D&ads.app_domain=%7BAPP_DOMAIN%7D&ads.app_name=%7BAPP_NAME%7D&ads.coppa=1"},
{"title":"<img src='https://i.imgur.com/OY6lWfQ.jpg' width='64px'height='36px'> As a Child","file":"https://kanlivep2event-i.akamaihd.net/hls/live/747600/747600/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/uBUHcE6.png' width='64px'height='36px'> Ketnet Jr","file":"https://content.uplynk.com/channel/e11a05356cc44198977436418ad71832.m3u8"},
{"title":"<img src='https://i.imgur.com/6Q5zLFf.jpg' width='64px'height='36px'> Kuriakos Kids","file":"http://c2.manasat.com:1935/kkids/kkids3/FluxusTV.m3u8"},
{"title":"<img src='https://i.imgur.com/1Iw6Jj6.jpg' width='64px'height='36px'> Kinder TV","file":"https://autopilot.catcast.tv/content/38144/index.m3u8"},
{"title":"<img src='https://i.imgur.com/mDff3aC.jpg' width='64px'height='36px'> Lale","file":"http://stream.atr.ua/lale/live/index.m3u8"},
{"title":"<img src='https://i.imgur.com/jjfubB7.jpg' width='64px'height='36px'> TRT Cocuk","file":"https://tv-trtcocuk.live.trt.com.tr/master.m3u8"},
{"title":"<img src='https://i.imgur.com/LNKhtAt.jpg' width='64px'height='36px'> TVG Infantil","file":"http://infantil-crtvg.flumotion.com/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/lhdFPDd.jpg' width='64px'height='36px'> Kabillion","file":"https://dai2.xumo.com/xumocdn/p=redbox&deviceid=&is_lat=&subp=RedboxdesktopWebWindows/amagi_hls_data_xumo1212A-redboxkabillion/CDN/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/LYW9d8H.png' width='64px'height='36px'> Battery Pop","file":"https://dai2.xumo.com/xumocdn/p=redbox&deviceid=&is_lat=&subp=RedboxdesktopWebWindows/amagi_hls_data_xumo1212A-redboxbatterypop/CDN/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/Po9G5Q5.jpg' width='64px'height='36px'> Rainbow Ruby","file":"https://dai2.xumo.com/xumocdn/p=redbox&deviceid=&is_lat=&subp=RedboxdesktopWebWindows/amagi_hls_data_xumo1212A-roku-rainbow-ruby/CDN/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/rY0YnYc.jpg' width='64px'height='36px'> Rakuten Kids & Family","file":"https://469cf88d4f4c4ba48207fdfd0f74f580.mediatailor.us-east-1.amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/Samsung-gb_RakutenFamily/playlist.m3u8?ads.wurl_channel=717&ads.wurl_name=RakutenFamily&ads.coppa=1&ads.psid=%7BPSID%7D&ads.targetopt=%7BTARGETOPT%7D&ads.app_domain=%7BAPP_DOMAIN%7D&ads.app_name=%7BAPP_NAME%7D&ads.consent=%7BTC_STRING%7D"},
{"title":"<img src='https://i.imgur.com/Dd2RlCp.jpg' width='64px'height='36px'> Kidsflix","file":"https://stream-us-east-1.getpublica.com/playlist.m3u8?network_id=50"}
]},
{"title":"Cooking","folder":
[
{"title":"<img src='https://i.imgur.com/JhAeaUr.jpg' width='64px'height='36px'> So Yummy","file":"https://dai2.xumo.com/xumocdn/p=redbox&deviceid=&is_lat=&subp=RedboxdesktopWebWindows/amagi_hls_data_xumo1212A-redboxsoyummy/CDN/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/SVlKgfu.jpg' width='64px'height='36px'> Rasi Lifestyle TV","file":"http://singamcloud.in:1935/rasinetwork/cookings/chunklist.m3u8"},
{"title":"<img src='https://i.imgur.com/DEMFJqW.jpg' width='64px'height='36px'> Bite","file":"https://cdn-ue1-prod.tsv2.amagi.tv/linear/amg01478-parademediagrou-bite-samsunguk/playlist.m3u8?ads.did=%7BPSID%7D&ads.dnt=%7BTARGETOPT%7D&ads.app_domain=%7BAPP_DOMAIN%7D&ads.app_name=%7BAPP_NAME%7D&ads.tc_string=%7BTC_STRING%7D&ads.coppa=0"},
{"title":"<img src='https://i.imgur.com/6U2jrbk.jpg' width='64px'height='36px'> Tastemade","file":"https://tastemadeintaus-smindia.amagi.tv/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/XpSNwns.png' width='64px'height='36px'> Food Food","file":"https://m-c07-j2apps.s.llnwi.net/hls/7005.FoodFoodChannel.in.m3u8"},
{"title":"<img src='https://i.imgur.com/ZAz46qu.png' width='64px'height='36px'> Food Network","file":"https://sbshdlu5-lh.akamaihd.net/i/sbshdl_6@1000854/master.m3u8?sd=10&rebase=on&mux_audio=true"}
]},
{"title":"Sports","folder":
[
{"title":"<img src='https://i.imgur.com/xSBUzRB.png' width='64px'height='36px'> FOX Sport News AUS","file":"https://austchannel-live.akamaized.net/hls/live/2002736/austchannel-sport/master.m3u8"},
{"title":"<img src='https://i.imgur.com/FW8KOQr.png' width='64px'height='36px'> DD Sports","file":"http://103.199.161.254/Content/ddsports/Live/Channel(DDSPORTS)/index.m3u8"},
{"title":"<img src='https://i.imgur.com/XwnDHUi.png' width='64px'height='36px'> NESN+","file":"https://bcovlive-a.akamaihd.net/f1fe983d710642b08c2232d4f5e1bb49/us-east-1/6141518204001/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/Jl3Cak5.png' width='64px'height='36px'> Tennis","file":"https://tennischannel-intl-samsung-uk.amagi.tv/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/2H1OYMQ.png' width='64px'height='36px'> NBC Golf","file":"http://edge.linknetott.swiftserve.com/live/BSgroup/amlst:hich/chunklist.m3u8"},
{"title":"<img src='https://i.imgur.com/KykBzDz.png' width='64px'height='36px'> Dubai Racing","file":"https://dmisvthvll.cdn.mangomolo.com/events/smil:events.smil/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/WEsYR0a.png' width='64px'height='36px'> Redbull TV","file":"https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8"},
{"title":"<img src='https://i.imgur.com/dXLuuPF.png' width='64px'height='36px'> Edge Sports","file":"https://img-edgesport.samsung.wurl.com/manifest/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/twA7iRj.png' width='64px'height='36px'> FTF For the fans","file":"https://elevensports-uk.samsung.wurl.com/manifest/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/Uqmp4xE.jpg' width='64px'height='36px'> Dubai Sports 1","file":"https://dmitnthvll.cdn.mangomolo.com/dubaisports/smil:dubaisports.smil/master.m3u8"},
{"title":"<img src='https://i.imgur.com/egzmCOQ.jpg' width='64px'height='36px'> Dubai Sports 2","file":"https://dmitwlvvll.cdn.mangomolo.com/dubaisportshd/smil:dubaisportshd.smil/master.m3u8"},
{"title":"<img src='https://i.imgur.com/F8fyKxT.jpg' width='64px'height='36px'> Dubai Sports 3","file":"https://dmitwlvvll.cdn.mangomolo.com/dubaisportshd5/smil:dubaisportshd5.smil/master.m3u8"},
{"title":"<img src='https://i.imgur.com/uH8LLD7.jpg' width='64px'height='36px'> Ad Sports 1","file":"https://admdn1.cdn.mangomolo.com/adsports1/smil:adsports1.stream.smil/master.m3u8"},
{"title":"<img src='https://i.imgur.com/qIrEXix.jpg' width='64px'height='36px'> Ad Sports 2","file":"https://admdn5.cdn.mangomolo.com/adsports2/smil:adsports2.stream.smil/master.m3u8"},
{"title":"<img src='https://i.imgur.com/A8iWBuM.jpg' width='64px'height='36px'> Ad Sports 3","file":"https://admdn3.cdn.mangomolo.com/adsports3/smil:adsports3.stream.smil/master.m3u8"},
{"title":"<img src='https://i.imgur.com/tKAAihn.jpg' width='64px'height='36px'> TNT Sports 1","file":"https://glxlmn026c.singularcdn.net.br/playout_01/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/5qjThCC.jpg' width='64px'height='36px'> TNT Sports 2","file":"https://glxlmn026c.singularcdn.net.br/playout_02/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/Szghe15.jpg' width='64px'height='36px'> TNT Sports 3","file":"https://glxlmn026c.singularcdn.net.br/playout_03/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/L8VoVI0.jpg' width='64px'height='36px'> TNT Sports 4","file":"https://glxlmn026c.singularcdn.net.br/playout_04/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/XY9XeFc.jpg' width='64px'height='36px'> TNT Sports 5","file":"https://glxlmn026c.singularcdn.net.br/playout_05/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/GFZrR1p.jpg' width='64px'height='36px'> Arriadia","file":"https://cdnamd-hls-globecast.akamaized.net/live/ramdisk/arriadia/hls_snrt/index.m3u8"},
{"title":"<img src='https://i.imgur.com/b2t4TYc.jpg' width='64px'height='36px'> Sharjah Sports","file":"https://svs.itworkscdn.net/smc4sportslive/smc4.smil/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/iiWgxf6.jpg' width='64px'height='36px'> QAZSPORT","file":"http://92.46.127.146:8080/qazsport/index.m3u8"},
{"title":"<img src='https://i.imgur.com/7qETrZK.png' width='64px'height='36px'> World Of Free Sports TV","file":"https://a.jsrdn.com/broadcast/ab14783a09/+0000/c.m3u8"}
]},
{"title":"Infotainment","folder":
[
{"title":"<img src='https://i.imgur.com/kUVht1i.png' width='64px'height='36px'> PBS America","file":"https://pbs-samsunguk.amagi.tv/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/BQDdzat.jpg' width='64px'height='36px'> Love Nature","file":"https://bamus-eng-roku.amagi.tv/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/OTfBYZS.png' width='64px'height='36px'> Go USA","file":"https://d3f5a0c8f3fa46b2be317d584c2fff6b.mediatailor.us-east-1.amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/Samsung-gb_GoUSATV/playlist.m3u8?ads.wurl_channel=535&ads.wurl_name=GoUSATV&ads.psid=%7BPSID%7D&ads.targetopt=%7BTARGETOPT%7D&ads.app_domain=%7BAPP_DOMAIN%7D&ads.app_name=%7BAPP_NAME%7D&ads.coppa=0&ads.consent=%7BTC_STRING%7D"},
{"title":"<img src='https://i.imgur.com/NGvowyy.png' width='64px'height='36px'> Wild Life","file":"https://d1vp12yk4i8ou5.cloudfront.net/v1/master/3722c60a815c199d9c0ef36c5b73da68a62b09d1/WildLife2-prod/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/24EcV0h.jpg' width='64px'height='36px'> Wild Earth","file":"https://wildearth-plex.amagi.tv/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/waa9pN7.png' width='64px'height='36px'> KET","file":"https://2-fss-1.streamhoster.com/pl_134/amlst:200914-1282960/playlist.m3u8?DVR"},
{"title":"<img src='https://i.imgur.com/0xWnPXJ.png' width='64px'height='36px'> People are Awesome","file":"https://caeee1dd0eea4dde9429074e7f8e96bb.mediatailor.us-east-1.amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/Samsung-in_PeopleAreAwesome/playlist.m3u8?ads.wurl_channel=386&ads.wurl_name=PeopleAreAwesome&ads.coppa=0&ads.psid=%7BPSID%7D&ads.targetopt=%7BTARGETOPT%7D&ads.app_domain=%7BAPP_DOMAIN%7D&ads.app_name=%7BAPP_NAME%7D"},
{"title":"<img src='https://i.imgur.com/AWtXHHC.jpg' width='64px'height='36px'> Fireside","file":"https://fireside.localnowlive.com/v1/master/385c85a93929f94966d0fb186fc33b431e6f1eb9/DSP_5fdd393a31300f16077a1692_fireside/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/5Gb1YPQ.jpg' width='64px'height='36px'> Naturescape","file":"https://dai2.xumo.com/xumocdn/p=redbox&deviceid=&is_lat=&subp=RedboxdesktopWebWindows/amagi_hls_data_xumo1212A-redboxstingraynaturescape/CDN/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/uE9vHb6.jpg' width='64px'height='36px'> escapes","file":"https://dai2.xumo.com/xumocdn/p=redbox&deviceid=&is_lat=&subp=RedboxdesktopWebWindows/amagi_hls_data_xumo1212A-escapes/CDN/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/Op9R5OJ.jpg' width='64px'height='36px'> Zen","file":"https://ln-zen.localnowlive.com/v1/master/385c85a93929f94966d0fb186fc33b431e6f1eb9/DSP_5fd8fd0625dd2a6b74008872_ln-zen/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/sDYP89Y.png' width='64px'height='36px'> ChiveTV","file":"https://dai2.xumo.com/xumocdn/p=redbox&deviceid=&is_lat=&subp=RedboxdesktopWebWindows/amagi_hls_data_xumo1212A-redboxchive/CDN/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/bE2ajGw.jpg' width='64px'height='36px'> NASA TV Public","file":"http://hls.ums.ustream.tv/playlist/directhls/channel/6540154/playlist.m3u8?sgn=31d0dfb847c358d4cedcd2256dc4e1c42a7f13a7"},
{"title":"<img src='https://i.imgur.com/dEXuHFs.jpg' width='64px'height='36px'> Space Channel","file":"https://stream.ads.ottera.tv/playlist.m3u8?network_id=540"},
{"title":"<img src='https://i.imgur.com/YnIkbl5.png' width='64px'height='36px'> Humanity","file":"https://cdn-ue1-prod.tsv2.amagi.tv/linear/amg00712-alchimie-humanitydocuk-samsunguk/playlist.m3u8?ads.did=%7BPSID%7D&ads.dnt=%7BTARGETOPT%7D&ads.app_domain=%7BAPP_DOMAIN%7D&ads.app_name=%7BAPP_NAME%7D&ads.tc_string=%7BTC_STRING%7D&ads.coppa=0"},
{"title":"<img src='https://i.imgur.com/3RJJB0e.png' width='64px'height='36px'> Insight","file":"https://insighttv-samsung-uk.amagi.tv/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/T7JYL1s.png' width='64px'height='36px'> Inwild","file":"https://inwild-samsung-uk.amagi.tv/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/lB1QOS5.png' width='64px'height='36px'> Inwonder","file":"https://inwonder-samsung-uk.amagi.tv/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/YSg1dj3.png' width='64px'height='36px'> Introuble","file":"https://cdn-ue1-prod.tsv2.amagi.tv/linear/samsungin-introuble-samsungindia/playlist.m3u8?ads.did=%7BPSID%7D&ads.dnt=%7BTARGETOPT%7D&ads.app_domain=%7BAPP_DOMAIN%7D&ads.app_name=%7BAPP_NAME%7D&ads.coppa=0"},
{"title":"<img src='https://i.imgur.com/CFla6tq.png' width='64px'height='36px'> Outdoor channel","file":"https://outdoorchannel-samsungau.amagi.tv/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/o9szVeE.png' width='64px'height='36px'> FidoTV","file":"https://fidotv-roku.amagi.tv/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/AwkeusR.png' width='64px'height='36px'> Travel & Lifestyle","file":"https://dai2.xumo.com/xumocdn/p=redbox&deviceid=&is_lat=&subp=RedboxdesktopWebWindows/amagi_hls_data_xumo1212A-redboxxumotravellifestyle/CDN/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/JmxgZE6.jpg' width='64px'height='36px'> Tastemade Travel","file":"https://tastemadetravel-vizio.amagi.tv/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/gh5nXJF.jpg' width='64px'height='36px'> Go Traveler","file":"https://dai2.xumo.com/xumocdn/p=redbox&deviceid=&is_lat=&subp=RedboxdesktopWebWindows/amagi_hls_data_xumo1212A-redboxgotraveler/CDN/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/p4SRu81.png' width='64px'height='36px'> Xplore","file":"https://xlpore-samsungus.amagi.tv/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/NZkPH1N.png' width='64px'height='36px'> Travel XP","file":"https://17f510c554f64f82a337896666d59b8f.mediatailor.us-east-1.amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/Samsung-gb_TravelXP/playlist.m3u8?ads.wurl_channel=473&ads.wurl_name=TravelXP&ads.psid=%7BPSID%7D&ads.targetopt=%7BTARGETOPT%7D&ads.app_domain=%7BAPP_DOMAIN%7D&ads.app_name=%7BAPP_NAME%7D&ads.coppa=0&ads.consent=%7BTC_STRING%7D"},
{"title":"<img src='https://i.imgur.com/RmkRpST.jpg' width='64px'height='36px'> Million Dollar Listing","file":"https://d202koqm588atp.cloudfront.net/v1/master/3fec3e5cac39a52b2132f9c66c83dae043dc17d4/prod-samsungtvplus-stitched-publica/samsungtvplus_us_milliondollarlisting_001.m3u8?ads.caid=MillionDollarListing&ads.csid=samsungtvplus_us_milliondollarlisting_ssai&ads.xumo_platform=samsung&ads._fw_is_lat=%7BTARGETOPT%7D&ads._fw_us_privacy=1YNY&ads._fw_coppa=0&ads._fw_did=%7BPSID%7D&ads._fw_content_category=IAB1-7&ads._fw_content_genre=television&ads._fw_content_language=en&ads._fw_content_rating=tv-g&ads._fw_deviceMake=samsung&ads._fw_gdpr=0&ads.appName=%7BAPP_NAME%7D&ads.xumo_contentId=2780&ads.xumo_contentName=nbcumilliondollarlisting&ads.xumo_providerId=2780&ads.xumo_providerName=nbcumilliondollarlisting&ads.xumo_channelId=9999548&ads.xumo_channelName=Milliondollarlisting&ads.xumo_adsystem=mediatailor&ads.tpcl=MIDROLL&ads._fw_app_store_url=%7BAPP_DOMAIN%7D"},
{"title":"<img src='https://i.imgur.com/PlfARKr.png' width='64px'height='36px'> Lively Place","file":"https://7692a37649e54bef83adeea10f21aef0.mediatailor.us-east-1.amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/Samsung_LivelyPlace/playlist.m3u8?ads.wurl_channel=285&ads.wurl_name=LivelyPlace&ads.us_privacy=1YNY&ads.psid=%7BPSID%7D&ads.targetopt=%7BTARGETOPT%7D&ads.app_domain=%7BAPP_DOMAIN%7D&ads.app_name=%7BAPP_NAME%7D&ads.coppa=0"},
{"title":"<img src='https://i.imgur.com/Mq4klo5.png' width='64px'height='36px'> Tiny House Nation","file":"https://4f2d358e390a41cd8e87e74a954d9624.mediatailor.us-east-1.amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/Samsung_TinyHouseNation/playlist.m3u8?ads.wurl_channel=675&ads.wurl_name=TinyHouseNation&ads.coppa=0&ads.us_privacy=1YNY&ads.psid=%7BPSID%7D&ads.targetopt=%7BTARGETOPT%7D&ads.app_domain=%7BAPP_DOMAIN%7D&ads.app_name=%7BAPP_NAME%7D"},
{"title":"<img src='https://i.imgur.com/KoEHyry.png' width='64px'height='36px'> This Old House","file":"https://26487f8be0614420a64b6f5964563a75.mediatailor.us-east-1.amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/Samsung_ThisOldHouse/playlist.m3u8?ads.wurl_channel=180&ads.wurl_name=ThisOldHouse&ads.us_privacy=1YNY&ads.psid=%7BPSID%7D&ads.targetopt=%7BTARGETOPT%7D&ads.app_domain=%7BAPP_DOMAIN%7D&ads.app_name=%7BAPP_NAME%7D&ads.coppa=0"},
{"title":"<img src='https://i.imgur.com/cEivnzT.png' width='64px'height='36px'> The Design Network","file":"https://e60c9a5d763348c6a86c6d98fce3c52a.mediatailor.us-east-1.amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/Samsung_TheDesignNetwork/playlist.m3u8?ads.wurl_channel=295&ads.wurl_name=TheDesignNetwork&ads.us_privacy=1YNY&ads.psid=%7BPSID%7D&ads.targetopt=%7BTARGETOPT%7D&ads.app_domain=%7BAPP_DOMAIN%7D&ads.app_name=%7BAPP_NAME%7D&ads.coppa=0"},
{"title":"<img src='https://i.imgur.com/3ueF9nv.jpg' width='64px'height='36px'> Luxury HD","file":"http://nano.teleservice.su:8080/hls/luxury.m3u8"},
{"title":"<img src='https://i.imgur.com/J0Eee3n.jpg' width='64px'height='36px'> Architectural Digest ","file":"https://dai2.xumo.com/xumocdn/p=redbox&deviceid=&is_lat=&subp=RedboxdesktopWebWindows/amagi_hls_data_xumo1212A-redboxarchitecturaldigest/CDN/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/aWF5h37.jpg' width='64px'height='36px'> Architectural Digest ","file":"https://dai2.xumo.com/xumocdn/p=redbox&deviceid=&is_lat=&subp=RedboxdesktopWebWindows/amagi_hls_data_xumo1212A-rokutraveler/CDN/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/6kVfWuP.jpg' width='64px'height='36px'> Craftistry","file":"https://studio71-craftistry-roku.amagi.tv/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/VBsHphj.png' width='64px'height='36px'> Kite Victers","file":"https://932y4x26ljv8-hls-live.5centscdn.com/victers/tv.stream/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/ZcJcRro.jpg' width='64px'height='36px'> Magellan TV","file":"https://6ad725dc59bb4e5c99db85fb2607a3f7.mediatailor.us-east-1.amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/Samsung_MagellanTV/playlist.m3u8?ads.us_privacy=1YNY&ads.wurl_channel=304&ads.wurl_name=MagellanTV&ads.psid=%7BPSID%7D&ads.targetopt=%7BTARGETOPT%7D&ads.app_domain=%7BAPP_DOMAIN%7D&ads.app_name=%7BAPP_NAME%7D&ads.coppa=0"},
{"title":"<img src='https://i.imgur.com/qfPEnBi.png' width='64px'height='36px'> Planet Knowledge","file":"https://5591df34695b4451a3a21e0fecb11830.mediatailor.us-east-1.amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/Samsung-gb_PlanetKnowledge/playlist.m3u8?ads.wurl_channel=392&ads.wurl_name=PlanetKnowledge&ads.psid=%7BPSID%7D&ads.targetopt=%7BTARGETOPT%7D&ads.app_domain=%7BAPP_DOMAIN%7D&ads.app_name=%7BAPP_NAME%7D&ads.coppa=0&ads.consent=%7BTC_STRING%7D"},
{"title":"<img src='https://i.imgur.com/QSTsuaC.png' width='64px'height='36px'> Silence TV","file":"http://93.190.140.42:8081/SilenceTV/live/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/lLvf7aV.jpg' width='64px'height='36px'> Just for Laughs Gags","file":"https://dai2.xumo.com/xumocdn/p=redbox&deviceid=&is_lat=&subp=RedboxdesktopWebLinux/amagi_hls_data_xumo1212A-redboxjustforlaughsgags/CDN/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/aQb8sen.png' width='64px'height='36px'> FailArmy","file":"https://d89ea9d7a37f40408057298b5ea93acc.mediatailor.us-east-1.amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/Samsung-in_FailArmy/playlist.m3u8?ads.wurl_channel=151&ads.wurl_name=FailArmy&ads.coppa=0&ads.psid=%7BPSID%7D&ads.targetopt=%7BTARGETOPT%7D&ads.app_domain=%7BAPP_DOMAIN%7D&ads.app_name=%7BAPP_NAME%7D"},
{"title":"<img src='https://i.imgur.com/iBU6tPd.png' width='64px'height='36px'> Journy","file":"https://vcnovation.teleosmedia.com/linear/ovation/journy/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/IJTKZeW.png' width='64px'height='36px'> WayPoint","file":"https://06da9118165f4d71b2ff89588ea26323.mediatailor.us-east-1.amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/Samsung-ca_WaypointTV/playlist.m3u8?ads.wurl_channel=231&ads.wurl_name=WaypointTV&ads.psid=%7BPSID%7D&ads.targetopt=%7BTARGETOPT%7D&ads.app_domain=%7BAPP_DOMAIN%7D&ads.app_name=%7BAPP_NAME%7D&ads.coppa=0"},
{"title":"<img src='https://i.imgur.com/bug0mYD.jpg' width='64px'height='36px'> Accu Weather","file":"https://cdn-ue1-prod.tsv2.amagi.tv/linear/amg00684-accuweather-accuweather-plex/playlist.m3u8?us_privacy=1---&did=62274240-07e7-5d94-8dc8-ef68cf19e175&dnt=0&X-Plex-Token=K3jFyttsksLzRwtohyrJ&channelId=6151d74593dbf246f0843f01"},
{"title":"<img src='https://i.imgur.com/cDtN3lO.png' width='64px'height='36px'> Weather Spy","file":"https://eab55cb96c3d436a99afc4c6f9e27252.mediatailor.us-east-1.amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/Samsung-in_WeatherSpy/playlist.m3u8?ads.wurl_channel=388&ads.wurl_name=WeatherSpy&ads.coppa=0&ads.psid=%7BPSID%7D&ads.targetopt=%7BTARGETOPT%7D&ads.app_domain=%7BAPP_DOMAIN%7D&ads.app_name=%7BAPP_NAME%7D"},
{"title":"<img src='https://i.imgur.com/y51YkXk.png' width='64px'height='36px'> Agro TV","file":"https://agrotv.streamnet.ro/mobile_tv/agrotv.m3u8"},
{"title":"<img src='https://i.imgur.com/4nfWQ20.png' width='64px'height='36px'> Agro Brasil TV","file":"http://45.162.230.234:1935/agrobrasiltv/agrobrasiltv/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/73ID9oy.png' width='64px'height='36px'> Terra Viva","file":"http://186.234.127.82:1935/band_live/terraviva/master.m3u8"},
{"title":"<img src='https://i.imgur.com/Y0jnHh2.png' width='64px'height='36px'> Choppertown","file":"https://linear-11.frequency.stream/dist/plex/11/hls/master/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/wyrw1tL.jpg' width='64px'height='36px'> Skills+ Thrills","file":"https://f2886f2b044a4d2d91d501260e0ba14c.mediatailor.us-east-1.amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/Samsung_SkillsAndThrills/playlist.m3u8?ads.wurl_channel=590&ads.wurl_name=SkillsAndThrills&ads.us_privacy=1YNY&ads.psid=%7BPSID%7D&ads.targetopt=%7BTARGETOPT%7D&ads.app_domain=%7BAPP_DOMAIN%7D&ads.app_name=%7BAPP_NAME%7D&ads.coppa=0"},
{"title":"<img src='https://i.imgur.com/2eInoRi.jpg' width='64px'height='36px'> RakutenTV Spotlight","file":"https://a08e742423dc48aea37cfab512a3ef39.mediatailor.us-east-1.amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/Samsung-gb_RakutenSpotlight/playlist.m3u8?ads.wurl_channel=426&ads.wurl_name=RakutenSpotlight&ads.psid=%7BPSID%7D&ads.targetopt=%7BTARGETOPT%7D&ads.app_domain=%7BAPP_DOMAIN%7D&ads.app_name=%7BAPP_NAME%7D&ads.coppa=0&ads.consent=%7BTC_STRING%7D"},
{"title":"<img src='https://i.imgur.com/hccXIcQ.jpg' width='64px'height='36px'> Holiday Movie","file":"https://cb4e445b1fdc49a4a94f06ccc35f9c5f.mediatailor.us-east-1.amazonaws.com/v1/master/04fd913bb278d8775298c26fdca9d9841f37601f/Samsung_HolidayMovieFavoritesbyLifetime/playlist.m3u8?ads.wurl_channel=999&ads.wurl_name=HolidayMovieFavoritesbyLifetime&ads.coppa=0&ads.us_privacy=1YNY&ads.psid=%7BPSID%7D&ads.targetopt=%7BTARGETOPT%7D&ads.app_domain=%7BAPP_DOMAIN%7D&ads.app_name=%7BAPP_NAME%7D"}
]},
{"title":"News","folder":
[
{"title":"<img src='https://i.imgur.com/1noSKW3.png' width='64px'height='36px'> NDTV 24X7","file":"https://ndtv24x7elemarchana.akamaized.net/hls/live/2003678/ndtv24x7/ndtv24x7master.m3u8"},
{"title":"<img src='https://i.imgur.com/G4VlpP2.png' width='64px'height='36px'> Times NOW","file":"https://timesnow-lh.akamaihd.net/i/TNHD_1@129288/master.m3u8"},
{"title":"<img src='https://i.imgur.com/7UPdASO.png' width='64px'height='36px'> Mirror NOW","file":"https://mbnowweb-lh.akamaihd.net/i/MRN_1@346545/master.m3u8"},
{"title":"<img src='https://i.imgur.com/8DKBUG4.jpg' width='64px'height='36px'> India Today","file":"https://indiatodaylive.akamaized.net/hls/live/2014320/indiatoday/indiatodaylive/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/9rFXYvK.png' width='64px'height='36px'> News X","file":"https://itvoign.multitvsolution.com/hls/newsx.m3u8"},
{"title":"<img src='https://i.imgur.com/CYQmxln.png' width='64px'height='36px'> ET Now","file":"https://etnowweblive-lh.akamaihd.net/i/ETN_1@348070/master.m3u8"},
{"title":"<img src='https://i.imgur.com/VZp1Irh.png' width='64px'height='36px'> CNBC TV 18","file":"https://cnbctv18-lh.akamaihd.net/i/cnbctv18_1@174868/index_5_av-p.m3u8"},
{"title":"<img src='https://i.imgur.com/Sd7Js6T.png' width='64px'height='36px'> NDTV Profit","file":"https://ndtvprofitelemarchana.akamaized.net/hls/live/2003680/ndtvprofit/ndtvprofitmaster.m3u8"},
{"title":"<img src='https://i.imgur.com/eOpbTh8.jpg' width='64px'height='36px'> News7 Tamil","file":"https://versewsa.pc.cdn.bitgravity.com/versewsa/live/tamilnews7.smil/chunklist.m3u8"},
{"title":"<img src='https://i.imgur.com/z4BS4hR.jpg' width='64px'height='36px'> Kalaignar Seidhigal","file":"https://versewsa.pc.cdn.bitgravity.com/versewsa/live/kalaignar_tv.smil/chunklist.m3u8"},
{"title":"<img src='https://i.imgur.com/4D4tG97.png' width='64px'height='36px'> News18 Tamil","file":"https://news18tamil-lh.akamaihd.net/i/n18tamil_1@526595/index_5_av-p.m3u8"},
{"title":"<img src='https://i.imgur.com/N8teqYE.png' width='64px'height='36px'> Polimer News","file":"https://versewsa.pc.cdn.bitgravity.com/versewsa/live/polimernews.smil/chunklist.m3u8"},
{"title":"<img src='https://i.imgur.com/k4iewrs.png' width='64px'height='36px'> Malai Murasu","file":"https://m-c06-j2apps.s.llnwi.net/hls/7074.MalaiMurasuTV.in.m3u8"},
{"title":"<img src='https://i.imgur.com/Zf2ooX4.png' width='64px'height='36px'> Thanthi TV","file":"https://vidcdn.vidgyor.com/thanthi-origin/liveabr/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/xGjl1T1.png' width='64px'height='36px'> Pudhiya Thalaimurai","file":"https://versewsa.pc.cdn.bitgravity.com/versewsa/live/puthiyathalaimurai.smil/chunklist.m3u8"},
{"title":"<img src='https://i.imgur.com/NZeAvBi.png' width='64px'height='36px'> CBS News","file":"https://cbsn-us-cedexis.cbsnstream.cbsnews.com/out/v1/55a8648e8f134e82a470f83d562deeca/master.m3u8"},
{"title":"<img src='https://i.imgur.com/KJyrdZW.png' width='64px'height='36px'> CNN","file":"https://cnn-cnninternational-1-de.samsung.wurl.com/manifest/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/eeHQjFV.png' width='64px'height='36px'> Fox News Now","file":"https://fox-foxnewsnow-samsungus.amagi.tv/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/Z3InuIH.png' width='64px'height='36px'> Sky News","file":"http://skydvn-sn-mobile-prod.skydvn.com/skynews/1404/latest.m3u8"},
{"title":"<img src='https://i.imgur.com/sX5dE44.png' width='64px'height='36px'> Euro News","file":"https://rakuten-euronews-1-gb.samsung.wurl.com/manifest/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/xXnl9Vb.png' width='64px'height='36px'> CBN News","file":"https://bcliveunivsecure-lh.akamaihd.net/i/news_1@500579/master.m3u8"},
{"title":"<img src='https://i.imgur.com/Sxyp3cs.png' width='64px'height='36px'> France24","file":"http://f24hls-i.akamaihd.net/hls/live/221147/F24_EN_HI_HLS/master.m3u8"},
{"title":"<img src='https://i.imgur.com/JvMORcf.png' width='64px'height='36px'> DW English","file":"https://dwamdstream102.akamaized.net/hls/live/2015525/dwstream102/index.m3u8"},
{"title":"<img src='https://i.imgur.com/TnHGaxT.png' width='64px'height='36px'> CNA","file":"https://d2e1asnsl7br7b.cloudfront.net/7782e205e72f43aeb4a48ec97f66ebbe/index.m3u8"},
{"title":"<img src='https://i.imgur.com/oP2jc4C.png' width='64px'height='36px'> NHK World Japan","file":"https://nhkw-zh-hlscomp.akamaized.net/8thz5iufork8wjip/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/mg0JahH.png' width='64px'height='36px'> Al Jazeera","file":"https://live-hls-web-aje.getaj.net/AJE/index.m3u8"},
{"title":"<img src='https://i.imgur.com/TcBIb23.jpg' width='64px'height='36px'> PTV World","file":"https://live.ptv.com.pk/live/ptvworld/master.m3u8"},
{"title":"<img src='https://i.imgur.com/SdwEFjq.png' width='64px'height='36px'> VOA","file":"https://voa-lh.akamaihd.net/i/voa_mpls_tvmc6@320298/master.m3u8"},
{"title":"<img src='https://i.imgur.com/9G9j9wU.png' width='64px'height='36px'> CGTN English","file":"https://news.cgtn.com/resource/live/english/cgtn-news.m3u8"},
{"title":"<img src='https://i.imgur.com/l5Zef9B.png' width='64px'height='36px'> CGTN Documentary","file":"https://news.cgtn.com/resource/live/document/cgtn-doc.m3u8"},
{"title":"<img src='https://i.imgur.com/Pn0UWp9.png' width='64px'height='36px'> TRT World","file":"https://tv-trtworld.live.trt.com.tr/master.m3u8"},
{"title":"<img src='https://i.imgur.com/7CmXtzU.png' width='64px'height='36px'> Australia Channel","file":"https://austchannel-live.akamaized.net/hls/live/2002729/austchannel-news/master.m3u8"}
]},
{"title":"Extra","folder":
[
{"title":"<img src='https://i.imgur.com/HdIDbk7.png' width='64px'height='36px'> Salvation TV","file":"https://d39bpvuye592vg.cloudfront.net/live.m3u8"},
{"title":"<img src='https://i.imgur.com/XQY3ysh.png' width='64px'height='36px'> TBN","file":"https://api.new.livestream.com/accounts/27460990/events/8266920/live.m3u8?Faith"},
{"title":"<img src='https://i.imgur.com/UGyo26g.jpg' width='64px'height='36px'> Hillsong Channel","file":"https://api.new.livestream.com/accounts/27460990/events/8266909/live.m3u8?Faith"},
{"title":"<img src='https://i.imgur.com/mnkq9jj.jpg' width='64px'height='36px'> Smile TV","file":"https://api.new.livestream.com/accounts/27460990/events/8266916/live.m3u8?Faith"},
{"title":"<img src='https://i.imgur.com/tj5kcst.jpg' width='64px'height='36px'> Biznet Kids","file":"http://livestream.biznetvideo.net/biznet_kids/smil:kids.smil/chunklist_w417362857_b2256000_slen_tkYml6a2V5bGl2ZXN0YXJ0dGltZT0wJmJpemtleWxpdmVlbmR0aW1lPTAmYml6a2V5bGl2ZUN1c3RvbVBhcmFtZXRlcj1teVBhcmFtZXRlciZiaXprZXlsaXZlaGFzaD1xQXJpMU0yeHVfTUFsbkh3VlJ0T3MyNGxSOFlfSFNEaWpOMkNSTmdoaWZVbGxoWXFRU0Rsa2QwcUU4Q2tad3hD.m3u8"},
{"title":"<img src='https://i.imgur.com/3IYvqq0.jpg' width='64px'height='36px'> Nick Jr","file":"https://cdn1.mobiletv.bg/T5/bit/bit_794613_850k.m3u8"},
{"title":"<img src='https://i.imgur.com/wCjsXsd.jpg' width='64px'height='36px'> Biznet Adventure","file":"http://livestream.biznetvideo.net/biznet_adventure/smil:adventure.smil/playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/Ga8U50c.jpg' width='64px'height='36px'> Наша Сибирь","file":"https://strm.yandex.ru/kal/sibir/sibir0.m3u8"},
{"title":"<img src='https://i.imgur.com/25FQIlo.jpg' width='64px'height='36px'> AKC TV","file":"https://broadcast.blivenyc.com/speed/broadcast/22/mobile-playlist.m3u8"},
{"title":"<img src='https://i.imgur.com/TpuHbBT.jpg' width='64px'height='36px'> AKC TV Puppies","file":"https://broadcast.blivenyc.com/speed/broadcast/29/mobile-playlist.m3u8"}
]},
{"title":"YouTube Live","folder":
[
{"title":"<img src='https://i.imgur.com/XAXZIT2.png' width='64px'height='36px'> Amazing Facts TV","file":"https://www.youtube.com/embed/6sG5c9xoSlg"},
{"title":"<img src='https://i.imgur.com/ZkZ2w52.jpg' width='64px'height='36px'> Deep Focus","file":"https://www.youtube.com/embed/yfYjEkaN-1s"},
{"title":"<img src='https://i.imgur.com/u7lUa2N.jpg' width='64px'height='36px'> English Speeches","file":"https://www.youtube.com/embed/osCtkH5B7vA"},
{"title":"<img src='https://i.imgur.com/gPuHs6T.png' width='64px'height='36px'> Beautiful Piano Music","file":"https://www.youtube.com/embed/y7e-GC6oGhg"},
{"title":"<img src='https://i.imgur.com/HiPwJ45.png' width='64px'height='36px'> Relax Flute Music","file":"https://m.youtube.com/watch?v=e1n2vVG4PaM&list=PLiCkeo30HQ6uuJkcN2boMGDUbSWiPKg-9&t=0s"},
{"title":"<img src='https://i.imgur.com/0myeSwx.png' width='64px'height='36px'> Powervision TV","file":"https://www.youtube.com/embed/L42NP9a8paw"}
]},
{"title":"FM Radio","folder":
[
{"title":"Comforter Radio","file":"https://streamer.radio.co/sd887222ab/listen"},
{"title":"Inbam FM","file":"https://stream.radio.co/sf55ced545/listen"},
{"title":"Thuthi FM","file":"https://radio.garden/api/ara/content/listen/4k7jJXJy/channel.mp3"},
{"title":"TWR India","file":"https://fm.radio882.com/radio/8010/tamil.mp3"},
{"title":"Healer Radio","file":"https://azura.shoutca.st/radio/8430/healerradio.mp3"},
{"title":"JehovahRapha FM","file":"https://azura.shoutca.st/radio/8180/jehovahrapha.mp3"},
{"title":"Revive Radio Hindi","file":"https://gains.reviveradio.net/proxy/reviveradiohindi?mp=/stream"},
{"title":"Radio Mashi","file":"https://gains.reviveradio.net/proxy/radiomasih?mp=/stream"},
{"title":"Revive Radio Punjabi","file":"https://gains.reviveradio.net/proxy/revivepunjabi?mp=/stream"},
{"title":"Bible Radio","file":"https://radio.garden/api/ara/content/listen/l0yMCQzR/channel.mp3"},
{"title":"Christian Power Praise","file":"http://listen.christianpowerpraise.net/stream/7/"},
{"title":"Kids Christian Radio","file":"https://usa18.fastcast4u.com/proxy/loudcrymedia2?mp=/1"},
{"title":"Menorah Radio","file":"https://radio.garden/api/ara/content/listen/vBV6jH2Q/channel.mp3"},
{"title":"Lifelight Radio","file":"https://lifelightradio.radioca.st/stream"},
{"title":"FEBA Online","file":"https://stream.radio.co/s383f50ab3/listen"}
]} 
]
, poster:"https://i.imgur.com/kl6RAOh.jpg"});
  
function PlayerInit(){
      player.api("moveplaylist","channels");
          }
  	  if (screen.width < 641) {
                window.scroll({
                top: 0,
                left: 0,
                behavior: 'smooth'
                });
            }
